/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SavingsCreateNestedManyWithoutUsersInput } from "./SavingsCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { SpendingCreateNestedManyWithoutUsersInput } from "./SpendingCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SavingsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SavingsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SavingsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  savingsItems?: SavingsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SpendingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SpendingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SpendingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  spendings?: SpendingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
